import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { ThemeToggle } from "@/components/theme-modal";
import { Zap } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme=""
            enableSystem={false}
            disableTransitionOnChange
          >
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <div className="flex items-center justify-center">
                <Zap className="h-8 w-8 text-orange-500" />
                <span className="ml-2 text-xl font-bold text-foreground">
                  FitCoach Pro
                </span>
              </div>
              <nav className="ml-auto flex gap-4 sm:gap-6">
                <a
                  className="text-sm font-medium hover:text-orange-500 transition-colors"
                  href="#features"
                >
                  Features
                </a>
                <a
                  className="text-sm font-medium hover:text-orange-500 transition-colors"
                  href="#testimonials"
                >
                  Testimonials
                </a>
                <a
                  className="text-sm font-medium hover:text-orange-500 transition-colors"
                  href="#pricing"
                >
                  Pricing
                </a>
              </nav>
              <SignedOut>
                <SignInButton />
                <SignUpButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
              {/* <ThemeToggle /> */}
            </header>
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
